general =
{
        name = "DEVICE_NAME";
        ignore_volume_control = "yes";
};

sessioncontrol =
{
        run_this_before_entering_active_state = "/usr/local/bin/radio pause";
        run_this_after_exiting_active_state = "/usr/local/bin/radio play";
        active_state_timeout = 10.0;
};
